#-----------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.
#-----------------------------------------------------------------------------------------

version: '3'
services:
  docker-in-docker:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace

      # Forwarding the socket is the key to getting this to work
      - /var/run/docker.sock:/var/run/docker.sock 
    
    # Overrides default command so things don't shut down after the process ends - useful for debugging
    command: sleep infinity 
    
