version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: dev-container.dockerfile
    ports:
     - "8090:8090"
     - "8000:8000"
    volumes:
      - .:/app
    command: /bin/sh -c "while :; do sleep 5000; done"

