#-----------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.
#-----------------------------------------------------------------------------------------

version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  your-service-name-here:
    # Uncomment if you want to add a different Dockerfile in the .devcontainer folder
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    # Uncomment if you want to expose any additional ports. The snippet below exposes port 3000.
    # ports:
    #   - 3000:3000
    
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace

      # Forwarding the socket is optional, but lets docker work inside the container if you install the Docker CLI.
      # See the docker-in-docker-compose definition for details on how to install it.
      - /var/run/docker.sock:/var/run/docker.sock 

    # Overrides default command so things don't shut down after the process ends. Optional, but useful for debugging.
    command: sleep infinity 
 
