version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: dev-container.dockerfile
    ports:
     - "5000:5000"
     - "8000:8000"
    volumes:
      - .:/app
    command: sleep infinity
  redis:
    image: "redis:alpine"
