version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: dev-container.dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sleep infinity
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/db
 
