version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: dev-container.dockerfile
    ports:
     - "3000:3000"
     - "8000:8000"
    volumes:
      - .:/app
    command: sleep infinity
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db
 
