version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/db
 
